### ISSUE TITLE
Add array of successful auth timestamps to the POST

### ISSUE THREAD

**Issue by brackendawson** [somakeit/door-controller2#10]

**Comment by brackendawson** [comment]
And assigned_user tag

**Comment by brackendawson** [comment]
And "location"

**Comment by benjie** [comment]
Software will send something of this form to us

- First is a key which has been scanned twice - log the scans and increase the counter to the number provided
- Second is a key which was scanned once
- Third is a new key - add to database but don't assign to a user

```json
{
  "tags": {
    "abcdefg": {
      "assigned_user": "00003",
      "count": 7,
      "scans": [
        {
          "date": 123123123,
          "location": "door"
        },
        {
          "date": 123123456,
          "location": "lathe"
        }
      ]
    },
    "01234567": {
      "assigned_user": "00003",
      "count": 8,
      "scans": [
        {
          "date": 123123123,
          "location": "door"
        }
      ]
    },
    "newnew12": {
      "assigned_user": null,
      "count": 1,
      "sector_a_key_a": "a2V5IGEA",
      "sector_a_key_b": "a2V5IGIA",
      "sector_a_secret": "hoteEaISPm56KrcIX67fMWRWEm3GmZU=",
      "sector_a_sector": 1,
      "sector_b_key_a": "a2V5IGEA",
      "sector_b_key_b": "a2V5IGIA",
      "sector_b_secret": "fp6C+KijosMbvxMF9vo3cNS2c98oSGY=",
      "sector_b_sector": 2
    }
  }
}
```

**Comment by brackendawson** [comment]
http://www.commitstrip.com/wp-content/uploads/2015/10/Strip-Trouver-le-nom-de-variable-english650-final.jpg

**Comment by brackendawson** [comment]
closed by cf5dc4c

**Comment by brackendawson** [comment]
Due to roles, I will be sending this format:

    "9b8785b5": {
            "count": 4820,
            "scans": [
                {
                    "date": 1446162552,
                    "location": "door",
                    "result": "denied"
                }
            ],
        }

**Comment by benjie** [comment]
:+1:
