### ISSUE TITLE
Solve issues with time/clock skew

### ISSUE THREAD

**Issue by benjie** [somakeit/door-controller2#2]
Much of the script uses `time.time()` to determine the absolute time, however ntpd and various other things can mess with this giving inaccurate timings. Suggest switching to `os.times()`'s 5th entry

> `os.times()`
> Return a 5-tuple of floating point numbers indicating accumulated (processor or other) times, in seconds. The items are: user time, system time, children’s user time, children’s system time, and **elapsed real time since a fixed point in the past**, in that order. See the Unix manual page times(2)

**Comment by brackendawson** [comment]
Better to be good than rely on ntpd slew.
